/**
 * Reusable AI Provider Layer for CRIBR using Groq SDK
 * Grounded Reasoning with Qwen / Llama Models on Groq Infrastructure
 */
import Groq from "groq-sdk";

function cleanGroqContent(content: string): string {
  if (!content) return "";
  // Strip out thinking tags generated by reasoning models like Qwen
  return content.replace(/<think>[\s\S]*?<\/think>/gi, "").trim();
}

function convertProjectToMarkdown(projectContext: any): string {
  if (!projectContext) return "No project data available.";

  let md = `## ${projectContext.name || "Unknown Project"}\n\n`;

  // Core details
  md += `**Builder:** ${projectContext.builder_name || "Unknown"} (Grade: ${projectContext.builder_grade || "N/A"})\n`;
  md += `**RERA Project Name:** ${projectContext.rera_project_name || "N/A"}\n`;
  md += `**RERA Number:** ${projectContext.rera_number || "Under Verification"}\n`;
  md += `**Location:** ${projectContext.locality || "Unknown"}, ${projectContext.city || "Bangalore"}\n`;
  
  // Pricing & Configuration
  md += `\n### Pricing & Configuration\n`;
  md += `- **Minimum Price:** ${projectContext.min_price ? "₹" + projectContext.min_price : "Price on Request"}\n`;
  md += `- **Maximum Price:** ${projectContext.max_price ? "₹" + projectContext.max_price : "N/A"}\n`;
  md += `- **Price Per SqFt:** ${projectContext.price_per_sqft ? "₹" + projectContext.price_per_sqft : "N/A"}\n`;
  md += `- **Configurations:** ${projectContext.unit_types || "N/A"}\n`;
  
  // Project Metrics
  md += `\n### Project Metrics\n`;
  md += `- **Total Units:** ${projectContext.total_units || "N/A"}\n`;
  md += `- **Land Area:** ${projectContext.land_area_acres ? projectContext.land_area_acres + " Acres" : (projectContext.land_area_sqm ? projectContext.land_area_sqm + " Sqm" : "N/A")}\n`;
  md += `- **Density:** ${projectContext.unit_density_per_acre ? projectContext.unit_density_per_acre + " units/acre" : "N/A"}\n`;
  
  // Status & Timeline
  md += `\n### Status & Timeline\n`;
  md += `- **Start Date:** ${projectContext.project_start_date || "N/A"}\n`;
  md += `- **Possession Date:** ${projectContext.possession_date || "N/A"}\n`;
  md += `- **Construction Progress:** ${projectContext.construction_progress ? projectContext.construction_progress + "%" : "N/A"}\n`;

  // Risk & Compliance
  md += `\n### Risk & Compliance (Verified)\n`;
  md += `- **RERA Complaints:** ${projectContext.complaints_count ?? 0}\n`;
  md += `- **Land Litigation:** ${projectContext.land_litigation ? "Yes" : "None reported"}\n`;

  // Commute & Ratings
  md += `\n### Commute & Ratings\n`;
  md += `- **Nearest Tech Hub:** ${projectContext.nearest_office_hub || "N/A"}\n`;
  md += `- **Distance to Hub:** ${projectContext.distance_to_hub_km ? projectContext.distance_to_hub_km + " km" : "N/A"}\n`;
  md += `- **CRIBR Score:** ${projectContext.cribr_score ? projectContext.cribr_score + "/100" : "N/A"}\n`;
  md += `- **Google Rating:** ${projectContext.google_rating ? projectContext.google_rating + " Stars" : "N/A"}\n`;
  
  if (projectContext.google_review_summary) {
    md += `- **Review Summary:** ${projectContext.google_review_summary}\n`;
  }

  // Inject any extra fields dynamically so nothing is missed
  const skipKeys = new Set(["id", "name", "builder_name", "builder_grade", "rera_project_name", "rera_number", "locality", "city", "min_price", "max_price", "price_per_sqft", "unit_types", "total_units", "land_area_acres", "land_area_sqm", "unit_density_per_acre", "project_start_date", "possession_date", "construction_progress", "complaints_count", "land_litigation", "nearest_office_hub", "distance_to_hub_km", "cribr_score", "google_rating", "google_review_summary"]);
  
  const extraKeys = Object.keys(projectContext).filter(k => !skipKeys.has(k) && projectContext[k] !== null && projectContext[k] !== undefined);
  if (extraKeys.length > 0) {
    md += `\n### Additional Verified Details\n`;
    for (const key of extraKeys) {
      md += `- **${key}:** ${JSON.stringify(projectContext[key])}\n`;
    }
  }

  return md;
}

function convertResultSetToMarkdown(dataset: any[]): string {
  if (!dataset || dataset.length === 0) return "No projects found.";
  let md = "";
  dataset.forEach((p, i) => {
    md += `\n# PROJECT ${i + 1}\n`;
    md += convertProjectToMarkdown(p) + "\n\n---\n\n";
  });
  return md;
}

export class GroqAIProvider {
  private client: Groq | null = null;
  private primaryModel = "qwen/qwen3.6-27b";
  private fallbackModels = ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "groq/compound"];

  private getClient(): Groq | null {
    if (this.client) return this.client;
    // Read from env or fallback to active platform key
    const apiKey =
      process.env.GROQ_API_KEY ||
      "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";

    if (apiKey && apiKey.trim()) {
      try {
        console.log(`[GROQ INIT] process.env.GROQ_API_KEY exists?`, !!process.env.GROQ_API_KEY);
        this.client = new Groq({ apiKey: apiKey.trim() });
      } catch (err) {
        console.error("Failed to initialize Groq SDK:", err);
      }
    }
    return this.client;
  }

  private async checkAvailableModels(groq: Groq) {
    try {
      const models = await groq.models.list();
      console.log("=== Available Groq Models ===");
      console.log(models.data.map((m: any) => m.id).join(", "));
      console.log("=============================");
    } catch (e) {
      console.warn("Could not fetch available Groq models.");
    }
  }

  /**
   * Phase 1: Extract structured search intent using Groq JSON mode
   */
  async extractSearchIntent(query: string): Promise<any | null> {
    const groq = this.getClient();
    if (!groq) return null;

    const systemPrompt = `You are CRIBR's real estate search intent parser.
Extract structured search filters from the user's natural language property query.
Return JSON ONLY matching this schema:
{
  "locality": string | null,
  "unitType": string | null,
  "maxPriceINR": number | null,
  "minPriceINR": number | null,
  "minBuilderGrade": string | null,
  "maxDistanceHubKm": number | null,
  "nearestOfficeHub": string | null,
  "possessionYear": number | null,
  "maxComplaints": number | null,
  "builderName": string | null,
  "keywords": string[]
}`;

    const modelsToTry = [this.primaryModel, ...this.fallbackModels];

    for (const model of modelsToTry) {
      try {
        const completion = await groq.chat.completions.create({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `User query: "${query}"` }
          ],
          response_format: { type: "json_object" },
          temperature: 0.1,
        });

        const raw = completion.choices[0]?.message?.content || "";
        const cleaned = cleanGroqContent(raw);
        if (cleaned) {
          return JSON.parse(cleaned);
        }
      } catch (err: any) {
        console.warn(`Groq intent extraction failed with model ${model}:`, err?.message || err);
      }
    }

    return null;
  }

  /**
   * Intent Classification
   */
  async classifyIntent(userQuestion: string): Promise<string> {
    const groq = this.getClient();
    if (!groq) return "current_project";

    const systemPrompt = `Classify the user's question into ONE of the following categories:
- general_ai
- current_project
- property_comparison
- search_query
- out_of_scope

Return ONLY the category name as a plain string, nothing else.

Guidelines:
- general_ai: general questions about real estate concepts, buying property, home loans, RERA, taxes.
- current_project: questions about the specific property they are viewing (e.g., "is it good?", "builder?", "price?").
- property_comparison: comparing one project to others.
- search_query: asking to find/search for properties based on criteria.
- out_of_scope: anything NOT related to real estate, properties, or CRIBR (e.g., coding, recipes, history, weather, general chit-chat not about housing).`;

    try {
      const completion = await groq.chat.completions.create({
        model: "llama-3.1-8b-instant",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userQuestion }
        ],
        temperature: 0,
        max_tokens: 15,
      });
      const intent = (completion.choices[0]?.message?.content || "").trim().toLowerCase();
      if (intent.includes("out_of_scope")) return "out_of_scope";
      if (intent.includes("general_ai")) return "general_ai";
      if (intent.includes("property_comparison")) return "property_comparison";
      if (intent.includes("search_query")) return "search_query";
      return "current_project";
    } catch (e) {
      return "current_project";
    }
  }

  /**
   * Phase 2: Grounded Result-Set AI Assistant
   */
  async generateResultAssistantAnswer(
    query: string,
    filters: any,
    compactDataset: any[],
    userQuestion: string
  ): Promise<string | null> {
    const groq = this.getClient();
    if (!groq) return null;

    const intent = await this.classifyIntent(userQuestion);

    if (intent === "out_of_scope") {
      return "I'm CRIBR AI Property Advisor. I specialize in helping users understand, compare, and evaluate real estate projects available on CRIBR. I can't assist with unrelated topics.";
    }

    const systemPrompt = `You are CRIBR AI Property Advisor.

You ONLY answer using the verified project context supplied below.

Rules:
- Never invent information.
- Never use outside knowledge.
- Never ask the user for information already present in the context.
- If information is missing from the context, explicitly say:
  "This information is not available in the verified project data."
- Write naturally like an experienced property consultant.
- Explain your reasoning in plain language.
- Distinguish facts from recommendations.

ACTIVE SEARCH RESULT DATASET (${compactDataset.length} Projects):
${convertResultSetToMarkdown(compactDataset)}
`;

    const userMessage = `USER QUESTION: "${userQuestion}"
ORIGINAL SEARCH QUERY: "${query}"
APPLIED FILTERS: ${JSON.stringify(filters || {})}`;

    const modelsToTry = [this.primaryModel, ...this.fallbackModels];

    for (const model of modelsToTry) {
      try {
        console.log("========== RESULTS AI PIPELINE LOGGING ==========");
        console.log(`[1] INCOMING QUESTION: "${userQuestion}"`);
        console.log(`[2] CLASSIFIED INTENT: "${intent}"`);
        console.log(`[3] PROMPT TO GROQ:\n${systemPrompt}`);
        
        const completion = await groq.chat.completions.create({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userMessage }
          ],
          temperature: 0.2,
        });

        const raw = completion.choices[0]?.message?.content || "";
        console.log(`[4] RAW GROQ RESPONSE (Model: ${model}):\n${raw}`);
        
        const cleaned = cleanGroqContent(raw);
        console.log(`[5] FINAL CLEANED RESPONSE:\n${cleaned}`);
        console.log("=================================================");
        
        if (cleaned) return cleaned;
      } catch (err: any) {
        console.warn(`Groq results assistant failed with model ${model}:`, err?.message || err);
      }
    }



    console.error("All fallback Groq models failed for generateResultAssistantAnswer.");
    await this.checkAvailableModels(groq);
    throw new Error("Unable to connect to result set assistant. The AI service is currently unavailable. Please try again later.");
  }

  /**
   * Phase 3: Per-Project Deep Intelligence Assistant
   */
  async generateProjectAIAnswer(
    projectContext: any,
    userQuestion: string
  ): Promise<string | null> {
    const groq = this.getClient();
    if (!groq) return null;

    const intent = await this.classifyIntent(userQuestion);

    if (intent === "out_of_scope") {
      return "I'm CRIBR AI Property Advisor. I specialize in helping users understand, compare, and evaluate real estate projects available on CRIBR. I can't assist with unrelated topics.";
    }

    const systemPrompt = `You are CRIBR AI Property Advisor.

You ONLY answer using the verified project context supplied below.

Rules:
- Never invent information.
- Never use outside knowledge.
- Never ask the user for information already present in the context.
- If information is missing from the context, explicitly say:
  "This information is not available in the verified project data."
- Write naturally like an experienced property consultant.
- Explain your reasoning in plain language.
- Distinguish facts from recommendations.

VERIFIED PROJECT FACTSHEET:
${convertProjectToMarkdown(projectContext)}

User intent is classified as: ${intent}.`;

    const modelsToTry = [this.primaryModel, ...this.fallbackModels];

    for (const model of modelsToTry) {
      try {
        console.log("========== PROJECT AI PIPELINE LOGGING ==========");
        console.log(`[1] INCOMING QUESTION: "${userQuestion}"`);
        console.log(`[2] CLASSIFIED INTENT: "${intent}"`);
        console.log(`[3] PROMPT TO GROQ:\n${systemPrompt}`);
        
        const completion = await groq.chat.completions.create({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: `USER QUESTION: "${userQuestion}"` }
          ],
          temperature: 0.3,
        });

        const raw = completion.choices[0]?.message?.content || "";
        console.log(`[4] RAW GROQ RESPONSE (Model: ${model}):\n${raw}`);
        
        const cleaned = cleanGroqContent(raw);
        console.log(`[5] FINAL CLEANED RESPONSE:\n${cleaned}`);
        console.log("=================================================");
        
        if (cleaned) return cleaned;
      } catch (err: any) {
        console.warn(`Groq project AI failed with model ${model}:`, err?.message || err);
      }
    }



    console.error("All fallback Groq models failed for generateProjectAIAnswer.");
    await this.checkAvailableModels(groq);
    throw new Error("Unable to generate project intelligence. Our AI systems might be experiencing high traffic or the backend is unreachable. Please try again later.");
  }

  /**
   * General Conversational Real Estate Chat Answer
   */
  async generateChatAnswer(userPrompt: string): Promise<string | null> {
    const groq = this.getClient();
    if (!groq) return null;

    const intent = await this.classifyIntent(userPrompt);

    if (intent === "out_of_scope") {
      return "I'm CRIBR AI Property Advisor. I specialize in helping users understand, compare, and evaluate real estate projects available on CRIBR. I can't assist with unrelated topics.";
    }

    const systemPrompt = `You are CRIBR AI Property Advisor.
You are not a generic chatbot. You specialize ONLY in helping users evaluate residential real estate projects.

Your knowledge comes ONLY from:
- Current project data
- Search results supplied
- Verified RERA information
- Builder information
- CRIBR Intelligence

Rules:
1. Never invent facts.
2. Never answer unrelated questions.
3. If asked something outside real estate, politely explain your scope.
4. Answer naturally.
5. Explain rather than list fields.
6. Mention uncertainty if data is missing.
7. Always cite which project you are discussing.
8. Maintain conversation context.
9. Speak like an experienced property consultant.
10. Never expose internal IDs or raw database fields.

User intent is classified as: ${intent}.
The user should feel like they are talking to an experienced property advisor.`;

    const modelsToTry = [this.primaryModel, ...this.fallbackModels];

    for (const model of modelsToTry) {
      try {
        const completion = await groq.chat.completions.create({
          model,
          messages: [
            { role: "system", content: systemPrompt },
            { role: "user", content: userPrompt }
          ],
          temperature: 0.3,
        });

        const raw = completion.choices[0]?.message?.content || "";
        const cleaned = cleanGroqContent(raw);
        if (cleaned) return cleaned;
      } catch (err: any) {
        console.warn(`Groq chat failed with model ${model}:`, err?.message || err);
      }
    }



    console.error("All fallback Groq models failed for generateChatAnswer.");
    await this.checkAvailableModels(groq);
    throw new Error("AI Chat failed to respond. The service might be experiencing high traffic.");
  }
}

export const aiProvider = new GroqAIProvider();
