import { FullProject } from "./types/search";

export const MASTER_PROJECTS: FullProject[] = [
  {
    id: "proj-godrej-lakeside-orchard",
    rank: 1,
    name: "Godrej Lakeside Orchard",
    builder: "Godrej Properties",
    developer: "Godrej Properties",
    category: "Luxury",
    description: "Top-tier builder reliability with pristine RERA compliance and low density.",
    price: "₹1.15 Cr - ₹2.45 Cr",
    aiScore: 94,
    configurations: "2 BHK, 3 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    builderId: "builder-godrej",
    location: "Sarjapur Road, Bangalore",
    localityName: "Sarjapur Road",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/240918/007085",
    priceRange: "₹1.15 Cr - ₹2.45 Cr",
    minPriceLakhs: 115,
    maxPriceLakhs: 245,
    pricePerSqft: "₹10,500/sqft",
    densityValue: 48,
    densityText: "48 units/acre",
    commuteScore: 9.2,
    commuteText: "4.5 km to Wipro SEZ / Sarjapur Hub",
    builderGrade: "A+",
    reliabilityScore: 94,
    constructionProgress: 35,
    possessionDate: "Dec 2028",
    googleRating: 4.6,
    reviewsCount: 320,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "940 Units",
    totalAcres: 14.5,
    status: "safe",
    statusText: "RERA Verified - Clean Title Deed",
    delayMonths: 0,
    pros: ["100% Litigation-free clear land title", "Lakeside greenery view", "Low unit density design"],
    cons: ["Peak hour traffic at Sarjapur junction"],
    amenities: ["Grand Clubhouse", "Infinity Swimming Pool", "Tennis Court", "Co-working Space", "EV Charging Stations"],
    schools: [
      { name: "Greenwood High International", distance: "2.1 km" },
      { name: "The International School Bangalore (TISB)", distance: "3.5 km" }
    ],
    metroDistance: "4.2 km (Upcoming Pink Line)",
    hospitalDistance: "3.1 km (Manipal Hospital)",
    investmentScore: 93,
    rentalYieldPercent: 4.8,
    futureGrowthText: "Sarjapur-ORR Metro extension will boost capital values by 18-22% over 3 years.",
    safeToBuy: true,
    aiVerdict: "STRONG BUY. Top-tier builder reliability with pristine RERA compliance and low density.",
    cribrScore: 94,
    cribrScoreBreakdown: {
      builderReliability: 96,
      constructionProgress: 35,
      locationTransit: 92,
      appreciationYield: 94,
      reraSafety: 100,
      densityLivability: 90
    },
    winnerBadges: {
      isOverallWinner: true,
      isBestValue: true,
      isBestInvestment: true
    },
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"
    ],
    aiInsights: [
      {
        type: "positive",
        title: "Clean RERA Title Deed",
        description: "Zero active land litigation reported across Karnataka RERA and BBMP records."
      },
      {
        type: "investment",
        title: "High Rental Yield Corridor",
        description: "Located within 15 minutes of major tech parks with high corporate tenant demand."
      }
    ],
    mapCoords: { x: 45, y: 52 },
    timeline: [
      { phase: "Land Title Verification", status: "completed", date: "Jan 2024", description: "Clear title deed certified" },
      { phase: "RERA Registration", status: "completed", date: "Sep 2024", description: "RERA PRM/KA/RERA/1251/308/PR/240918/007085" },
      { phase: "Foundation & Excavation", status: "in_progress", date: "Mar 2025", description: "35% structural progress completed" }
    ],
    documents: [
      { title: "RERA Approval Certificate", type: "RERA Certificate", verified: true, fileSize: "2.4 MB" },
      { title: "Environmental Clearance Certificate", type: "Environmental Clearance", verified: true, fileSize: "1.8 MB" }
    ],
    reviews: [
      { id: "rev-1", author: "Rajesh Kumar", date: "Jan 2025", rating: 5, comment: "Excellent layout planning with low density.", verifiedBuyer: true }
    ]
  },
  {
    id: "proj-nambiar-district-25",
    rank: 2,
    name: "Nambiar District 25 Ph.1",
    builder: "Nambiar Builders",
    developer: "Nambiar Builders",
    category: "Luxury",
    description: "Exceptional township master plan with strong long-term appreciation.",
    price: "₹1.40 Cr - ₹3.10 Cr",
    aiScore: 92,
    configurations: "2 BHK, 3 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    builderId: "builder-nambiar",
    location: "Chandapura - Muthanallur Road, Sarjapur, Bangalore",
    localityName: "Sarjapur",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/240402/006760",
    priceRange: "₹1.40 Cr - ₹3.10 Cr",
    minPriceLakhs: 140,
    maxPriceLakhs: 310,
    pricePerSqft: "₹11,200/sqft",
    densityValue: 42,
    densityText: "42 units/acre",
    commuteScore: 8.9,
    commuteText: "6.0 km to Outer Ring Road Tech Parks",
    builderGrade: "A",
    reliabilityScore: 91,
    constructionProgress: 28,
    possessionDate: "June 2029",
    googleRating: 4.5,
    reviewsCount: 240,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "1,200 Units",
    totalAcres: 100,
    status: "safe",
    statusText: "RERA Verified - 100-Acre Township",
    delayMonths: 0,
    pros: ["Integrated 100-acre mega township", "Mivan high-grade construction", "High open space ratio"],
    cons: ["Slightly longer distance to existing metro stations"],
    amenities: ["Sports Complex", "Olympic Size Pool", "Shopping Mall Inside", "Skating Rink", "Clubhouse"],
    schools: [{ name: "Inventure Academy", distance: "3.0 km" }],
    metroDistance: "6.5 km",
    hospitalDistance: "4.0 km",
    investmentScore: 91,
    rentalYieldPercent: 4.5,
    futureGrowthText: "Township ecosystems historically outperform single standalone projects in appreciation.",
    safeToBuy: true,
    aiVerdict: "BUY. Exceptional township master plan with strong long-term appreciation.",
    cribrScore: 92,
    cribrScoreBreakdown: {
      builderReliability: 90,
      constructionProgress: 28,
      locationTransit: 88,
      appreciationYield: 92,
      reraSafety: 100,
      densityLivability: 94
    },
    winnerBadges: {
      isOverallWinner: false,
      isBestValue: true,
      isBestLuxury: true
    },
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"
    ],
    aiInsights: [
      { type: "positive", title: "Mega Township Advantage", description: "Self-sustained ecosystem with retail, schools, and commercial zones." }
    ],
    mapCoords: { x: 60, y: 40 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-birla-evara",
    rank: 3,
    name: "Birla Evara",
    builder: "Birla Estates",
    developer: "Birla Estates",
    category: "Luxury",
    description: "Pristine developer track record with ultra-premium specifications.",
    price: "₹1.25 Cr - ₹2.80 Cr",
    aiScore: 95,
    configurations: "2 BHK, 3 BHK",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    builderId: "builder-birla",
    location: "Sarjapur Road, Bangalore",
    localityName: "Sarjapur Road",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/240510/006820",
    priceRange: "₹1.25 Cr - ₹2.80 Cr",
    minPriceLakhs: 125,
    maxPriceLakhs: 280,
    pricePerSqft: "₹11,800/sqft",
    densityValue: 45,
    densityText: "45 units/acre",
    commuteScore: 9.1,
    commuteText: "3.8 km to Electronic City Connector",
    builderGrade: "A+",
    reliabilityScore: 95,
    constructionProgress: 20,
    possessionDate: "Mar 2029",
    googleRating: 4.7,
    reviewsCount: 180,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "580 Units",
    totalAcres: 12.0,
    status: "safe",
    statusText: "RERA Verified - Century Legacy Brand",
    delayMonths: 0,
    pros: ["Century-old corporate governance", "Pre-certified Green Building", "Superior floor-to-ceiling heights"],
    cons: ["Premium pricing per sqft compared to local builders"],
    amenities: ["Biophilic Clubhouse", "Therapeutic Gardens", "Heated Swimming Pool", "Pet Park"],
    schools: [{ name: "Oakridge International School", distance: "2.8 km" }],
    metroDistance: "3.9 km",
    hospitalDistance: "2.5 km",
    investmentScore: 94,
    rentalYieldPercent: 4.9,
    futureGrowthText: "Birla brand positioning guarantees high resale velocity.",
    safeToBuy: true,
    aiVerdict: "BUY. Pristine developer track record with ultra-premium specifications.",
    cribrScore: 95,
    cribrScoreBreakdown: {
      builderReliability: 98,
      constructionProgress: 20,
      locationTransit: 90,
      appreciationYield: 95,
      reraSafety: 100,
      densityLivability: 92
    },
    winnerBadges: {
      isBestLuxury: true
    },
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 30, y: 65 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-sobha-royal-pavilion",
    rank: 4,
    name: "Sobha Royal Pavilion",
    builder: "Sobha Developers",
    developer: "Sobha Developers",
    category: "Ready to Move",
    description: "STRONG BUY for immediate occupancy with zero completion risk.",
    price: "₹1.15 Cr - ₹2.20 Cr",
    aiScore: 93,
    configurations: "2 BHK, 3 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    builderId: "builder-sobha",
    location: "Sarjapur Road, Bangalore",
    localityName: "Sarjapur Road",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/190204/002338",
    priceRange: "₹1.15 Cr - ₹2.20 Cr",
    minPriceLakhs: 115,
    maxPriceLakhs: 220,
    pricePerSqft: "₹12,400/sqft",
    densityValue: 52,
    densityText: "52 units/acre",
    commuteScore: 9.3,
    commuteText: "3.2 km to Wipro SEZ",
    builderGrade: "A+",
    reliabilityScore: 96,
    constructionProgress: 90,
    possessionDate: "Ready to Move",
    googleRating: 4.7,
    reviewsCount: 410,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "1,284 Units",
    totalAcres: 24.0,
    status: "ready",
    statusText: "Ready to Move - Immediate Handover",
    delayMonths: 0,
    pros: ["Self-construction backward integration", "Rajasthani palace architecture", "Immediate rental income"],
    cons: ["Higher maintenance charges"],
    amenities: ["Grand Palace Clubhouse", "Swimming Pools", "Squash Court", "Amphitheatre"],
    schools: [{ name: "Chrysalis High", distance: "1.5 km" }],
    metroDistance: "3.0 km",
    hospitalDistance: "2.0 km",
    investmentScore: 92,
    rentalYieldPercent: 5.2,
    futureGrowthText: "Immediate occupancy with high existing rental yields.",
    safeToBuy: true,
    aiVerdict: "STRONG BUY for immediate occupancy with zero completion risk.",
    cribrScore: 93,
    cribrScoreBreakdown: {
      builderReliability: 98,
      constructionProgress: 90,
      locationTransit: 94,
      appreciationYield: 90,
      reraSafety: 100,
      densityLivability: 88
    },
    winnerBadges: {
      isBestRentalYield: true
    },
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 50, y: 50 },
    timeline: [],
    documents: [],
    reviews: []
  }
];

export function getFeaturedProperties(): FullProject[] {
  return MASTER_PROJECTS;
}

export const FEATURED_PROPERTIES = MASTER_PROJECTS;
export const INTELLIGENCE_REPORTS: any[] = [];
export const PREMIUM_PROPERTIES: any[] = MASTER_PROJECTS;
export const INTELLIGENCE_MODULES = PREMIUM_PROPERTIES;
