import { FullProject } from "./types/search";

export const MASTER_PROJECTS: FullProject[] = [
  {
    id: "proj-godrej-lakeside-orchard",
    rank: 1,
    name: "Godrej Lakeside Orchard",
    builder: "Godrej Properties Limited",
    developer: "Godrej Properties Limited",
    category: "Luxury",
    description: "Lakeside premium enclave on Sarjapur Road with 698 units and 21% construction completed.",
    price: "₹1.50 Cr - ₹2.79 Cr",
    aiScore: 88,
    configurations: "2 BHK, 3 BHK, 3.5 BHK",
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
    builderId: "builder-godrej-properties-limited",
    location: "Sarjapura Road, Bangalore",
    localityName: "Sarjapura Road",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/446/PR/300924/007105",
    priceRange: "₹1.50 Cr - ₹2.79 Cr",
    minPriceLakhs: 150,
    maxPriceLakhs: 279,
    pricePerSqft: "₹12,362/sqft",
    densityValue: 58,
    densityText: "58 units/acre",
    commuteScore: 8.8,
    commuteText: "3.43 km to Sarjapur Rd Hub",
    builderGrade: "A+",
    reliabilityScore: 92,
    constructionProgress: 21,
    possessionDate: "Sep 2030",
    googleRating: 3.6,
    reviewsCount: 320,
    complaintsCount: "2",
    activeComplaintsNum: 2,
    totalUnits: "698 Units",
    totalAcres: 12.1,
    status: "safe",
    statusText: "RERA Registered - Active Monitoring",
    delayMonths: 0,
    pros: ["Grade A+ promoter governance", "Direct lakefront access & open greenery", "High construction specification standard"],
    cons: ["2 active complaints in RERA portal", "Active land litigation flag under review"],
    amenities: ["Grand Lakeside Clubhouse", "Infinity Swimming Pool", "Tennis Court", "Co-working Space", "EV Charging Stations"],
    schools: [
      { name: "Greenwood High International", distance: "2.1 km" },
      { name: "The International School Bangalore (TISB)", distance: "3.5 km" }
    ],
    metroDistance: "4.2 km (Upcoming Pink Line)",
    hospitalDistance: "3.1 km (Manipal Hospital)",
    investmentScore: 87,
    rentalYieldPercent: 4.8,
    futureGrowthText: "Sarjapur-ORR Metro corridor extension expected to drive 18-22% capital growth.",
    safeToBuy: true,
    aiVerdict: "BUY WITH CAUTION. Strong brand and prime location, but verify title deeds regarding active land litigation.",
    cribrScore: 88,
    cribrScoreBreakdown: {
      builderReliability: 92,
      constructionProgress: 21,
      locationTransit: 90,
      appreciationYield: 91,
      reraSafety: 85,
      densityLivability: 89
    },
    winnerBadges: {
      isBestLuxury: true
    },
    images: [
      "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"
    ],
    aiInsights: [
      {
        type: "positive",
        title: "Prime Sarjapur Road Corridor",
        description: "3.43 km from core tech hubs with strong corporate executive rental demand."
      },
      {
        type: "warning",
        title: "Litigation & Complaint Flag",
        description: "2 recorded RERA complaints and land litigation note flagged for legal verification."
      }
    ],
    mapCoords: { x: 45, y: 52 },
    timeline: [
      { phase: "Project Start", status: "completed", date: "Nov 2024", description: "RERA registered and excavation initiated" },
      { phase: "Structure & Podium", status: "in_progress", date: "Mar 2026", description: "21% construction progress" },
      { phase: "Possession Handover", status: "upcoming", date: "Sep 2030", description: "Target completion date" }
    ],
    documents: [
      { title: "RERA Registration PRM/KA/RERA/1251/446/PR/300924/007105", type: "RERA Certificate", verified: true, fileSize: "2.4 MB" }
    ],
    reviews: [
      { id: "rev-1", author: "Rajesh K.", date: "Jan 2025", rating: 4, comment: "Spacious layout with pleasant lakefront views.", verifiedBuyer: true }
    ]
  },
  {
    id: "proj-nambiar-district-25-ph-1",
    rank: 2,
    name: "Nambiar District 25 Ph.1",
    builder: "Nambiar EnsembleResidential Projects LLP",
    developer: "Nambiar Builders",
    category: "Luxury",
    description: "Large-scale gated residential community in Dommasandra Village with 796 units.",
    price: "₹1.72 Cr - ₹3.46 Cr",
    aiScore: 91,
    configurations: "2 BHK, 2.5 BHK, 3 BHK, 3.5 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800",
    builderId: "builder-nambiar-ensembleresidential-projects-llp",
    location: "Dommasandra Village, Sarjapur Hobli, Bangalore",
    localityName: "Dommasandra Village, Sarjapur Hobli",
    city: "Bangalore",
    reraNumber: "RERA-PENDING-4",
    priceRange: "₹1.72 Cr - ₹3.46 Cr",
    minPriceLakhs: 172,
    maxPriceLakhs: 346,
    pricePerSqft: "₹13,850/sqft",
    densityValue: 90,
    densityText: "90 units/acre",
    commuteScore: 8.4,
    commuteText: "8.42 km to Sarjapur Rd",
    builderGrade: "A",
    reliabilityScore: 89,
    constructionProgress: 20,
    possessionDate: "Jan 2030",
    googleRating: 4.5,
    reviewsCount: 240,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "796 Units",
    totalAcres: 8.8,
    status: "safe",
    statusText: "Zero Litigation - 100% Clean Title",
    delayMonths: 0,
    pros: ["Zero consumer complaints or litigation", "Wide variety of 2BHK to 4BHK layouts", "Extensive lifestyle amenities"],
    cons: ["RERA registration filing in progress", "Higher density (90 units/acre)"],
    amenities: ["Sports Complex", "Olympic Size Pool", "Clubhouse", "Children Play Arena", "Jogging Track"],
    schools: [{ name: "Inventure Academy", distance: "3.0 km" }],
    metroDistance: "6.5 km",
    hospitalDistance: "4.0 km",
    investmentScore: 90,
    rentalYieldPercent: 4.6,
    futureGrowthText: "Sarjapur township expansion offers steady long-term appreciation.",
    safeToBuy: true,
    aiVerdict: "STRONG BUY. Clean title with zero complaints and comprehensive township infrastructure.",
    cribrScore: 91,
    cribrScoreBreakdown: {
      builderReliability: 89,
      constructionProgress: 20,
      locationTransit: 86,
      appreciationYield: 92,
      reraSafety: 94,
      densityLivability: 86
    },
    winnerBadges: {
      isBestValue: true
    },
    images: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"
    ],
    aiInsights: [
      { type: "positive", title: "Zero Litigation", description: "100% clean land title with zero RERA consumer disputes." }
    ],
    mapCoords: { x: 60, y: 40 },
    timeline: [
      { phase: "Start Date", status: "completed", date: "Jan 2025", description: "Ground work commenced" },
      { phase: "Possession", status: "upcoming", date: "Jan 2030", description: "Scheduled completion" }
    ],
    documents: [],
    reviews: []
  },
  {
    id: "proj-birla-evara",
    rank: 3,
    name: "Birla Evara",
    builder: "Vardhita Properties Pvt Ltd (Birla Estates)",
    developer: "Birla Estates",
    category: "Luxury",
    description: "Expansive 25.7-acre green luxury development by Birla Estates in Kodathi Village.",
    price: "₹93.20 Lakhs - ₹3.36 Cr",
    aiScore: 95,
    configurations: "1 BHK, 2 BHK, 3 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800",
    builderId: "builder-vardhita-properties-pvt-ltd-birla-estates",
    location: "Kodathi Village, Varthur Hobli, Bangalore",
    localityName: "Kodathi Village, Varthur Hobli",
    city: "Bangalore",
    reraNumber: "RERA-PENDING-5",
    priceRange: "₹93.20 Lakhs - ₹3.36 Cr",
    minPriceLakhs: 93.2,
    maxPriceLakhs: 336,
    pricePerSqft: "₹13,054/sqft",
    densityValue: 62,
    densityText: "62 units/acre",
    commuteScore: 9.3,
    commuteText: "2.99 km to Sarjapur Rd Hub",
    builderGrade: "A",
    reliabilityScore: 96,
    constructionProgress: 4,
    possessionDate: "Dec 2031",
    googleRating: 4.6,
    reviewsCount: 180,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "1,594 Units",
    totalAcres: 25.7,
    status: "safe",
    statusText: "Grade A Birla Governance - 25.7 Acres",
    delayMonths: 0,
    pros: ["Birla Estates century corporate governance", "Accessible entry price from ₹93.2L for 1BHK", "Massive 25.7 acre master plan with low density"],
    cons: ["Early stage construction (4% progress)", "Longer timeline to Dec 2031 possession"],
    amenities: ["Biophilic Clubhouse", "Heated Swimming Pool", "Therapeutic Gardens", "Pet Park", "Squash Courts"],
    schools: [{ name: "Oakridge International School", distance: "2.8 km" }],
    metroDistance: "3.9 km",
    hospitalDistance: "2.5 km",
    investmentScore: 95,
    rentalYieldPercent: 5.1,
    futureGrowthText: "Birla brand strength and strategic Kodathi location offer superior capital appreciation.",
    safeToBuy: true,
    aiVerdict: "TOP PICK. Stellar corporate governance, excellent entry pricing, and massive land parcel.",
    cribrScore: 95,
    cribrScoreBreakdown: {
      builderReliability: 98,
      constructionProgress: 15,
      locationTransit: 94,
      appreciationYield: 96,
      reraSafety: 97,
      densityLivability: 93
    },
    winnerBadges: {
      isOverallWinner: true,
      isBestInvestment: true,
      isBestLuxury: true
    },
    images: [
      "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800"
    ],
    aiInsights: [
      { type: "positive", title: "Brand & Governance", description: "Birla Estates backing ensures unmatched legal and construction reliability." }
    ],
    mapCoords: { x: 30, y: 65 },
    timeline: [
      { phase: "Launch & Foundation", status: "in_progress", date: "May 2025", description: "4% structural work" },
      { phase: "Handover", status: "upcoming", date: "Dec 2031", description: "Target completion" }
    ],
    documents: [],
    reviews: []
  },
  {
    id: "proj-prestige-eaton-park",
    rank: 4,
    name: "Prestige Eaton Park",
    builder: "Prestige Projects Pvt Ltd",
    developer: "Prestige Group",
    category: "Luxury",
    description: "Low-density enclave of 366 units inside The Prestige City township in Sarjapur Hobli.",
    price: "₹1.45 Cr - ₹2.90 Cr",
    aiScore: 93,
    configurations: "2 BHK, 3 BHK",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800",
    builderId: "builder-prestige-projects-pvt-ltd",
    location: "Sompura/Valagere Kalahalli, Sarjapur Hobli, Bangalore",
    localityName: "Sompura/Valagere Kalahalli, Sarjapur Hobli",
    city: "Bangalore",
    reraNumber: "RERA-PENDING-6",
    priceRange: "₹1.45 Cr - ₹2.90 Cr",
    minPriceLakhs: 145,
    maxPriceLakhs: 290,
    pricePerSqft: "₹12,100/sqft",
    densityValue: 48,
    densityText: "48 units/acre",
    commuteScore: 8.5,
    commuteText: "10.59 km to ITPL / Whitefield",
    builderGrade: "A+",
    reliabilityScore: 95,
    constructionProgress: 0,
    possessionDate: "Jun 2030",
    googleRating: 4.4,
    reviewsCount: 150,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "366 Units",
    totalAcres: 7.7,
    status: "safe",
    statusText: "Grade A+ Prestige City Township - Low Density",
    delayMonths: 0,
    pros: ["Prestigious township ecosystem", "Ultra-low density of only 48 units/acre", "Zero litigation record"],
    cons: ["Pre-launch phase with 0% construction", "10.59 km to core ITPL hub"],
    amenities: ["Prestige Club Access", "Township Retail Mall", "Multiplex", "Tennis Academy", "Central Parks"],
    schools: [{ name: "Head Start Educational Academy", distance: "3.2 km" }],
    metroDistance: "7.0 km",
    hospitalDistance: "4.5 km",
    investmentScore: 92,
    rentalYieldPercent: 4.7,
    futureGrowthText: "The Prestige City township has demonstrated rapid price appreciation across all completed phases.",
    safeToBuy: true,
    aiVerdict: "BUY. Prestige reliability and low-density enclave within a proven integrated township.",
    cribrScore: 93,
    cribrScoreBreakdown: {
      builderReliability: 96,
      constructionProgress: 10,
      locationTransit: 87,
      appreciationYield: 94,
      reraSafety: 95,
      densityLivability: 95
    },
    winnerBadges: {
      isBestValue: true
    },
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 70, y: 35 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-brigade-sanctuary",
    rank: 5,
    name: "Brigade Sanctuary",
    builder: "Brigade Enterprises Ltd",
    developer: "Brigade Group",
    category: "Luxury",
    description: "Rapidly progressing 14.9-acre community with 62% construction completed in Chikkavaderapura.",
    price: "₹1.60 Cr - ₹2.80 Cr",
    aiScore: 94,
    configurations: "3 BHK, 4 BHK+Maid",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800",
    builderId: "builder-brigade-enterprises-ltd",
    location: "Chikkavaderapura Village, Sarjapura Hobli, Bangalore",
    localityName: "Chikkavaderapura Village, Sarjapura Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/446/PR/041123/006372",
    priceRange: "₹1.60 Cr - ₹2.80 Cr",
    minPriceLakhs: 160,
    maxPriceLakhs: 280,
    pricePerSqft: "₹11,256/sqft",
    densityValue: 86,
    densityText: "86 units/acre",
    commuteScore: 8.9,
    commuteText: "7.76 km to Kadubeesanahalli / ORR",
    builderGrade: "A+",
    reliabilityScore: 96,
    constructionProgress: 62,
    possessionDate: "Dec 2028",
    googleRating: 4.5,
    reviewsCount: 310,
    complaintsCount: "3",
    activeComplaintsNum: 3,
    totalUnits: "1,275 Units",
    totalAcres: 14.9,
    status: "safe",
    statusText: "62% Construction Completed - On Track Dec 2028",
    delayMonths: 0,
    pros: ["Fast-tracked construction at 62% completed", "Grade A+ developer track record", "Competitive ₹11,256/sqft pricing"],
    cons: ["3 RERA complaints filed", "No 1BHK or 2BHK configurations"],
    amenities: ["Sanctuary Clubhouse", "Forest Trail", "Lap Pool", "Indoor Badminton Courts", "Amphitheatre"],
    schools: [{ name: "Chrysalis High", distance: "2.0 km" }],
    metroDistance: "5.5 km",
    hospitalDistance: "3.5 km",
    investmentScore: 93,
    rentalYieldPercent: 4.9,
    futureGrowthText: "High construction completion velocity significantly reduces delivery risk.",
    safeToBuy: true,
    aiVerdict: "STRONG BUY. Best combination of Grade A+ builder, advanced construction (62%), and solid value.",
    cribrScore: 94,
    cribrScoreBreakdown: {
      builderReliability: 96,
      constructionProgress: 62,
      locationTransit: 90,
      appreciationYield: 93,
      reraSafety: 92,
      densityLivability: 88
    },
    winnerBadges: {
      isBestValue: true
    },
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 55, y: 55 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-abhee-celestial-city",
    rank: 6,
    name: "Abhee Celestial City",
    builder: "Nexplace Infrastructure (Abhee Ventures)",
    developer: "Abhee Ventures",
    category: "Affordable",
    description: "Well-paced mid-segment residential development in Chikkavaderapura with 45% completion.",
    price: "₹1.50 Cr - ₹2.22 Cr",
    aiScore: 86,
    configurations: "2 BHK, 2.5 BHK, 3 BHK",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800",
    builderId: "builder-nexplace-infrastructure-abhee-ventures",
    location: "Chikkavaderapura Village, Sarjapura Hobli, Bangalore",
    localityName: "Chikkavaderapura Village, Sarjapura Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/071123/006380",
    priceRange: "₹1.50 Cr - ₹2.22 Cr",
    minPriceLakhs: 150,
    maxPriceLakhs: 222,
    pricePerSqft: "₹11,160/sqft",
    densityValue: 83,
    densityText: "83 units/acre",
    commuteScore: 8.9,
    commuteText: "7.57 km to Kadubeesanahalli",
    builderGrade: "B",
    reliabilityScore: 84,
    constructionProgress: 45,
    possessionDate: "Jun 2029",
    googleRating: 4.1,
    reviewsCount: 140,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "399 Units",
    totalAcres: 4.8,
    status: "safe",
    statusText: "45% Progress - Clean Track Record",
    delayMonths: 0,
    pros: ["Zero complaints and litigation", "Steady 45% construction progress", "Compact boutique community of 399 units"],
    cons: ["Grade B builder tier", "Smaller 4.8 acre footprint"],
    amenities: ["Sky Lounge", "Swimming Pool", "Fitness Center", "Children Play Area"],
    schools: [{ name: "Vidhya Niketan", distance: "2.4 km" }],
    metroDistance: "6.0 km",
    hospitalDistance: "3.8 km",
    investmentScore: 84,
    rentalYieldPercent: 4.6,
    futureGrowthText: "Close proximity to Sarjapur hub provides good rental prospects.",
    safeToBuy: true,
    aiVerdict: "BUY. Dependable mid-budget option with solid construction pace and clean compliance.",
    cribrScore: 86,
    cribrScoreBreakdown: {
      builderReliability: 82,
      constructionProgress: 45,
      locationTransit: 88,
      appreciationYield: 86,
      reraSafety: 94,
      densityLivability: 85
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 52, y: 58 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-assetz-melodies-of-life",
    rank: 7,
    name: "Assetz Melodies of Life",
    builder: "Iinspira Worldcity Projects Pvt Ltd (Assetz)",
    developer: "Assetz Property Group",
    category: "Luxury",
    description: "Boutique high-end residential tower in Choodasandra, just 1.49 km from Sarjapur Road.",
    price: "₹96.00 Lakhs - ₹3.36 Cr",
    aiScore: 89,
    configurations: "3 BHK only (2 towers), Plotted 600-2400 sqft",
    image: "https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800",
    builderId: "builder-iinspira-worldcity-projects-pvt-ltd-assetz",
    location: "Choodasandra Village, Sarjapur Hobli, Bangalore",
    localityName: "Choodasandra Village, Sarjapur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/310/PR/061225/008321",
    priceRange: "₹96.00 Lakhs - ₹3.36 Cr",
    minPriceLakhs: 96,
    maxPriceLakhs: 336,
    pricePerSqft: "₹15,567/sqft",
    densityValue: 60,
    densityText: "60 units/acre",
    commuteScore: 9.6,
    commuteText: "1.49 km to Sarjapur Rd Main",
    builderGrade: "B",
    reliabilityScore: 87,
    constructionProgress: 14,
    possessionDate: "Nov 2030",
    googleRating: 4.3,
    reviewsCount: 95,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "204 Units",
    totalAcres: 3.4,
    status: "safe",
    statusText: "Boutique 204 Units - 1.49 km to Sarjapur Rd",
    delayMonths: 0,
    pros: ["Superb location only 1.49 km from Sarjapur Road", "Low density exclusive 204 units", "Premium Assetz architecture"],
    cons: ["Premium rate of ₹15,567/sqft", "Early construction stage (14%)"],
    amenities: ["Rooftop Infinity Pool", "Clubhouse", "Yoga Deck", "Library", "Zen Garden"],
    schools: [{ name: "Primus Public School", distance: "1.8 km" }],
    metroDistance: "3.2 km",
    hospitalDistance: "2.2 km",
    investmentScore: 89,
    rentalYieldPercent: 5.0,
    futureGrowthText: "Prime location ensures high tenant demand and healthy capital growth.",
    safeToBuy: true,
    aiVerdict: "BUY. Premium boutique living with prime connectivity near Sarjapur Road.",
    cribrScore: 89,
    cribrScoreBreakdown: {
      builderReliability: 86,
      constructionProgress: 14,
      locationTransit: 96,
      appreciationYield: 90,
      reraSafety: 95,
      densityLivability: 92
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1576941089067-2de3c901e126?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 38, y: 70 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-dsr-the-address",
    rank: 8,
    name: "DSR The Address",
    builder: "DSR Infraprojects",
    developer: "DSR Infraprojects",
    category: "Affordable",
    description: "13.7-acre residential community in Thigalachodadenahalli with 34% construction completed.",
    price: "₹1.32 Cr - ₹3.15 Cr",
    aiScore: 85,
    configurations: "1 BHK, 2 BHK, 2.5 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=800",
    builderId: "builder-dsr-infraprojects",
    location: "Thigalachodadenahalli Village, Sarjapura Hobli, Bangalore",
    localityName: "Thigalachodadenahalli Village, Sarjapura Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/050924/006996",
    priceRange: "₹1.32 Cr - ₹3.15 Cr",
    minPriceLakhs: 132,
    maxPriceLakhs: 315,
    pricePerSqft: "₹11,527/sqft",
    densityValue: 51,
    densityText: "51 units/acre",
    commuteScore: 8.8,
    commuteText: "7.93 km to Kadubeesanahalli",
    builderGrade: "B",
    reliabilityScore: 83,
    constructionProgress: 34,
    possessionDate: "Jun 2029",
    googleRating: 4.2,
    reviewsCount: 110,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "702 Units",
    totalAcres: 13.7,
    status: "safe",
    statusText: "Low Density 51 units/acre - 34% Progress",
    delayMonths: 0,
    pros: ["Low density of 51 units/acre", "Broad configuration spectrum from 1BHK to 4BHK", "Zero litigation record"],
    cons: ["Grade B builder tier", "Moderate distance to Outer Ring Road"],
    amenities: ["Clubhouse", "Swimming Pool", "Badminton Court", "Party Lawn", "Gym"],
    schools: [{ name: "Delhi Public School East", distance: "3.5 km" }],
    metroDistance: "6.2 km",
    hospitalDistance: "4.1 km",
    investmentScore: 84,
    rentalYieldPercent: 4.5,
    futureGrowthText: "Steady appreciation expected along the Sarjapur-Varthur connector.",
    safeToBuy: true,
    aiVerdict: "BUY. Value proposition with low density and solid construction headway.",
    cribrScore: 85,
    cribrScoreBreakdown: {
      builderReliability: 82,
      constructionProgress: 34,
      locationTransit: 87,
      appreciationYield: 85,
      reraSafety: 94,
      densityLivability: 90
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1600565193348-f74bd3c7ccdf?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 50, y: 60 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-candeur-rise",
    rank: 9,
    name: "Candeur Rise",
    builder: "Candeur",
    developer: "Candeur Group",
    category: "Affordable",
    description: "Modern high-rise residential project in Varthur offering 1 BHK to 4 BHK configurations.",
    price: "₹1.32 Cr - ₹3.15 Cr",
    aiScore: 83,
    configurations: "1 BHK, 2 BHK, 2.5 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800",
    builderId: "builder-candeur",
    location: "Varthur, Bangalore",
    localityName: "Varthur",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/050924/006997",
    priceRange: "₹1.32 Cr - ₹3.15 Cr",
    minPriceLakhs: 132,
    maxPriceLakhs: 315,
    pricePerSqft: "₹11,527/sqft",
    densityValue: 51,
    densityText: "51 units/acre",
    commuteScore: 8.2,
    commuteText: "7.2 km to IT Corridors",
    builderGrade: "B",
    reliabilityScore: 81,
    constructionProgress: 0,
    possessionDate: "Dec 2030",
    googleRating: 4.0,
    reviewsCount: 80,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "702 Units",
    totalAcres: 13.7,
    status: "safe",
    statusText: "RERA Registered - Launch Phase",
    delayMonths: 0,
    pros: ["Spacious 13.7 acre land parcel", "Affordable entry rates in Varthur", "Zero consumer complaints"],
    cons: ["0% construction completed", "Long delivery horizon to Dec 2030"],
    amenities: ["Multipurpose Hall", "Swimming Pool", "Children Play Area", "Fitness Studio"],
    schools: [{ name: "Ryan International School", distance: "4.0 km" }],
    metroDistance: "6.8 km",
    hospitalDistance: "4.5 km",
    investmentScore: 82,
    rentalYieldPercent: 4.4,
    futureGrowthText: "Varthur infrastructure upgrades will benefit mid-term asset appreciation.",
    safeToBuy: true,
    aiVerdict: "HOLD/BUY. Decent pricing and clean title, though construction is at initial stages.",
    cribrScore: 83,
    cribrScoreBreakdown: {
      builderReliability: 80,
      constructionProgress: 5,
      locationTransit: 84,
      appreciationYield: 84,
      reraSafety: 92,
      densityLivability: 89
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 65, y: 48 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-nambiar-district-25-phase-3",
    rank: 10,
    name: "Nambiar District 25 Phase 3",
    builder: "Nambiar",
    developer: "Nambiar Builders",
    category: "Luxury",
    description: "1,202-unit modern residential township phase in Dommasandra Village, Sarjapur Hobli.",
    price: "₹1.69 Cr - ₹4.03 Cr",
    aiScore: 89,
    configurations: "2 BHK, 3 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800",
    builderId: "builder-nambiar",
    location: "Dommasandra Village, Sarjapur Hobli, Bangalore",
    localityName: "Dommasandra Village, Sarjapur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/260526/008686",
    priceRange: "₹1.69 Cr - ₹4.03 Cr",
    minPriceLakhs: 169,
    maxPriceLakhs: 403,
    pricePerSqft: "₹11,160/sqft",
    densityValue: 104,
    densityText: "104 units/acre",
    commuteScore: 8.9,
    commuteText: "7.12 km to Sarjapur Road Hub",
    builderGrade: "B",
    reliabilityScore: 86,
    constructionProgress: 0,
    possessionDate: "Feb 2032",
    googleRating: 4.5,
    reviewsCount: 160,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "1,202 Units",
    totalAcres: 11.5,
    status: "safe",
    statusText: "Township Phase 3 - Competitive ₹11,160/sqft",
    delayMonths: 0,
    pros: ["High rating (4.5★) praised for design and master layouts", "Attractive ₹11,160/sqft entry rate", "Full township amenity access"],
    cons: ["High density of 104 units/acre", "Long timeline to Feb 2032"],
    amenities: ["Grand Clubhouse", "Swimming Pool", "Cricket Pitch", "Badminton Arena", "Co-working Space"],
    schools: [{ name: "Inventure Academy", distance: "3.2 km" }],
    metroDistance: "6.0 km",
    hospitalDistance: "3.8 km",
    investmentScore: 89,
    rentalYieldPercent: 4.7,
    futureGrowthText: "Township expansion provides consistent long-term rental demand.",
    safeToBuy: true,
    aiVerdict: "BUY FOR INVESTMENT. Strong long-term capital compounding within a growing township.",
    cribrScore: 89,
    cribrScoreBreakdown: {
      builderReliability: 86,
      constructionProgress: 5,
      locationTransit: 88,
      appreciationYield: 91,
      reraSafety: 94,
      densityLivability: 82
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 58, y: 44 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-forest-province-2-mana-the-right-life",
    rank: 11,
    name: "Forest Province 2 @ Mana The Right Life",
    builder: "Mana Projects",
    developer: "Mana Projects",
    category: "Luxury",
    description: "Nature-inspired 526-unit residential community in Chikkavadera with spacious 3BHK to 4.5BHK units.",
    price: "₹1.90 Cr - ₹3.00 Cr",
    aiScore: 86,
    configurations: "3 BHK, 3 BHK+Study, 4 BHK, 4.5 BHK",
    image: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800",
    builderId: "builder-mana-projects",
    location: "Chikkavadera, Sarjapura Hobli, Bangalore",
    localityName: "Chikkavadera, Sarjapura Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/308/PR/120326/008522",
    priceRange: "₹1.90 Cr - ₹3.00 Cr",
    minPriceLakhs: 190,
    maxPriceLakhs: 300,
    pricePerSqft: "₹10,659/sqft",
    densityValue: 94,
    densityText: "94 units/acre",
    commuteScore: 8.8,
    commuteText: "7.77 km to Kadubeesanahalli",
    builderGrade: "B",
    reliabilityScore: 83,
    constructionProgress: 0,
    possessionDate: "Jun 2031",
    googleRating: 3.9,
    reviewsCount: 120,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "526 Units",
    totalAcres: 5.6,
    status: "safe",
    statusText: "Spacious Large Units - ₹10,659/sqft Value",
    delayMonths: 0,
    pros: ["Spacious family layouts including 3BHK+Study and 4.5BHK", "Very competitive ₹10,659/sqft rate", "Zero litigation record"],
    cons: ["Mixed reviews on booking clarity (3.9★)", "Pre-construction stage"],
    amenities: ["Forest Canopy Walk", "Clubhouse", "Swimming Pool", "Spa & Sauna", "Kids Play Area"],
    schools: [{ name: "Silver Oaks International", distance: "2.8 km" }],
    metroDistance: "6.2 km",
    hospitalDistance: "4.0 km",
    investmentScore: 85,
    rentalYieldPercent: 4.5,
    futureGrowthText: "Large luxury unit format in high demand for expanding tech executive families.",
    safeToBuy: true,
    aiVerdict: "BUY FOR FAMILIES. Excellent square footage value for large 3BHK and 4BHK requirements.",
    cribrScore: 86,
    cribrScoreBreakdown: {
      builderReliability: 82,
      constructionProgress: 5,
      locationTransit: 87,
      appreciationYield: 87,
      reraSafety: 93,
      densityLivability: 84
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 53, y: 52 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-east-park-residences",
    rank: 12,
    name: "East Park Residences",
    builder: "Ramsons Trendsquares",
    developer: "Ramsons Trendsquares",
    category: "Ready to Move",
    description: "Well-advanced 67% completed residential project in Kodathi with possession in March 2028.",
    price: "₹2.32 Cr - ₹3.31 Cr",
    aiScore: 88,
    configurations: "3 BHK, 3.5 BHK, 4 BHK+Maid",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800",
    builderId: "builder-ramsons-trendsquares",
    location: "Kodathi, Varthur Hobli, Bangalore",
    localityName: "Kodathi, Varthur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/310/PR/280224/006657",
    priceRange: "₹2.32 Cr - ₹3.31 Cr",
    minPriceLakhs: 232,
    maxPriceLakhs: 331,
    pricePerSqft: "₹13,892/sqft",
    densityValue: 75,
    densityText: "75 units/acre",
    commuteScore: 9.3,
    commuteText: "4.13 km to Kadubeesanahalli / ORR",
    builderGrade: "B",
    reliabilityScore: 85,
    constructionProgress: 67,
    possessionDate: "Mar 2028",
    googleRating: 4.0,
    reviewsCount: 175,
    complaintsCount: "2",
    activeComplaintsNum: 2,
    totalUnits: "497 Units",
    totalAcres: 6.6,
    status: "ready",
    statusText: "67% Completed - Near Possession Mar 2028",
    delayMonths: 0,
    pros: ["Advanced 67% construction completed", "Prime Kodathi location just 4.13 km to ORR tech parks", "Near delivery timeline"],
    cons: ["2 RERA complaints regarding finishing resolution", "Higher starting ticket (₹2.32 Cr)"],
    amenities: ["Sky Lounge", "Infinity Edge Pool", "Tennis Court", "Clubhouse", "Squash Court"],
    schools: [{ name: "Oakridge International", distance: "2.2 km" }],
    metroDistance: "4.5 km",
    hospitalDistance: "3.0 km",
    investmentScore: 88,
    rentalYieldPercent: 5.2,
    futureGrowthText: "Near delivery timeline allows quick rental yield realization.",
    safeToBuy: true,
    aiVerdict: "BUY FOR EARLY MOVE-IN. 67% completed with quick handover timeline to March 2028.",
    cribrScore: 88,
    cribrScoreBreakdown: {
      builderReliability: 84,
      constructionProgress: 67,
      locationTransit: 93,
      appreciationYield: 88,
      reraSafety: 89,
      densityLivability: 87
    },
    winnerBadges: {
      isBestRentalYield: true
    },
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 35, y: 62 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-arvind-sylva",
    rank: 13,
    name: "Arvind Sylva",
    builder: "Arvind Smarthomes",
    developer: "Arvind SmartSpaces",
    category: "Luxury",
    description: "Ultra-premium biophilic development in Mullur, Varthur Hobli boasting a 4.9★ Google rating.",
    price: "₹2.10 Cr - ₹3.09 Cr",
    aiScore: 92,
    configurations: "3 BHK, 4 BHK",
    image: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800",
    builderId: "builder-arvind-smarthomes",
    location: "Mullur, Varthur Hobli, Bangalore",
    localityName: "Mullur, Varthur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/446/PR/090726/008800",
    priceRange: "₹2.10 Cr - ₹3.09 Cr",
    minPriceLakhs: 210,
    maxPriceLakhs: 309,
    pricePerSqft: "₹13,450/sqft",
    densityValue: 80,
    densityText: "80 units/acre",
    commuteScore: 9.1,
    commuteText: "4.85 km to Kadubeesanahalli",
    builderGrade: "B",
    reliabilityScore: 91,
    constructionProgress: 0,
    possessionDate: "Aug 2031",
    googleRating: 4.9,
    reviewsCount: 18,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "374 Units",
    totalAcres: 4.7,
    status: "safe",
    statusText: "4.9★ Rated - RERA Approved Jul 2026",
    delayMonths: 0,
    pros: ["Highest rating (4.9★) for architecture and master plan", "Arvind corporate heritage brand", "Zero consumer complaints"],
    cons: ["Pre-launch development with 0% construction progress", "Possession target in Aug 2031"],
    amenities: ["Forest Pavilion", "Clubhouse", "Temperature Controlled Pool", "Yoga Studio", "Outdoor Cinema"],
    schools: [{ name: "Bethany High", distance: "3.1 km" }],
    metroDistance: "4.8 km",
    hospitalDistance: "3.2 km",
    investmentScore: 91,
    rentalYieldPercent: 4.8,
    futureGrowthText: "Arvind brand prestige guarantees high secondary market resale velocity.",
    safeToBuy: true,
    aiVerdict: "BUY. Pristine design, zero complaints, and exceptional buyer satisfaction ratings.",
    cribrScore: 92,
    cribrScoreBreakdown: {
      builderReliability: 90,
      constructionProgress: 5,
      locationTransit: 91,
      appreciationYield: 92,
      reraSafety: 96,
      densityLivability: 89
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 42, y: 60 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-the-earthscape-phase-1",
    rank: 14,
    name: "The Earthscape Phase-1",
    builder: "Bricks and Milestones",
    developer: "Bricks & Milestones",
    category: "Affordable",
    description: "Eco-centric 8.6-acre residential enclave in Gunjur with 648 units and 19% progress.",
    price: "₹1.65 Cr - ₹2.65 Cr",
    aiScore: 85,
    configurations: "2 BHK, 3 BHK, 3.5 BHK",
    image: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800",
    builderId: "builder-bricks-and-milestones",
    location: "Gunjur, Varthur Hobli, Bangalore",
    localityName: "Gunjur, Varthur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/446/PR/020925/008044",
    priceRange: "₹1.65 Cr - ₹2.65 Cr",
    minPriceLakhs: 165,
    maxPriceLakhs: 265,
    pricePerSqft: "₹11,633/sqft",
    densityValue: 75,
    densityText: "75 units/acre",
    commuteScore: 9.0,
    commuteText: "4.94 km to Kadubeesanahalli",
    builderGrade: "B",
    reliabilityScore: 84,
    constructionProgress: 19,
    possessionDate: "Aug 2030",
    googleRating: 4.3,
    reviewsCount: 130,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "648 Units",
    totalAcres: 8.6,
    status: "safe",
    statusText: "19% Progress - Clean Title Deed",
    delayMonths: 0,
    pros: ["19% structural progress underway", "Clean title with zero litigation", "Competitive ₹11,633/sqft rate"],
    cons: ["Narrow access road during peak hours in Gunjur", "Medium builder size"],
    amenities: ["Organic Farming Deck", "Clubhouse", "Swimming Pool", "Skating Track", "Gym"],
    schools: [{ name: "Gunjur Govt High School / Global Indian", distance: "2.5 km" }],
    metroDistance: "5.0 km",
    hospitalDistance: "3.5 km",
    investmentScore: 84,
    rentalYieldPercent: 4.6,
    futureGrowthText: "Gunjur road widening initiatives will significantly elevate regional property prices.",
    safeToBuy: true,
    aiVerdict: "BUY. Solid eco-friendly residential option in the emerging Gunjur corridor.",
    cribrScore: 85,
    cribrScoreBreakdown: {
      builderReliability: 82,
      constructionProgress: 19,
      locationTransit: 89,
      appreciationYield: 85,
      reraSafety: 94,
      densityLivability: 86
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 48, y: 50 },
    timeline: [],
    documents: [],
    reviews: []
  },
  {
    id: "proj-evergreen-prestige-raintree-park",
    rank: 15,
    name: "Evergreen @ Prestige Raintree Park",
    builder: "Prestige Group",
    developer: "Prestige Group",
    category: "Luxury",
    description: "Massive 24.7-acre flagship township in Varthur Hobli, just 1.71 km to ITPL / Whitefield.",
    price: "₹1.02 Cr - ₹3.90 Cr",
    aiScore: 96,
    configurations: "1 BHK, 2 BHK, 3 BHK, 4.5 BHK",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800",
    builderId: "builder-prestige-group",
    location: "Varthur Hobli, Bangalore",
    localityName: "Varthur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/446/PR/010126/008374",
    priceRange: "₹1.02 Cr - ₹3.90 Cr",
    minPriceLakhs: 102,
    maxPriceLakhs: 390,
    pricePerSqft: "₹15,500/sqft",
    densityValue: 81,
    densityText: "81 units/acre",
    commuteScore: 9.7,
    commuteText: "1.71 km to ITPL / Whitefield Tech Hub",
    builderGrade: "A",
    reliabilityScore: 97,
    constructionProgress: 8,
    possessionDate: "Jun 2030",
    googleRating: 4.2,
    reviewsCount: 380,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "2,000 Units",
    totalAcres: 24.7,
    status: "safe",
    statusText: "Grade A Flagship Township - 1.71 km to ITPL",
    delayMonths: 0,
    pros: ["Unmatched location 1.71 km from ITPL / Whitefield", "Vast 24.7 acre luxury township with lake views", "Wide options from ₹1.02 Cr 1BHK to ₹3.90 Cr 4.5BHK"],
    cons: ["Premium price point ₹15,500/sqft", "High traffic along Whitefield main road"],
    amenities: ["Grand 50,000 sqft Clubhouse", "Lake View Promenade", "Multiple Pools", "Bowling Alley", "Squash & Tennis Courts"],
    schools: [{ name: "The Deens Academy", distance: "2.0 km" }],
    metroDistance: "2.1 km (Whitefield Metro)",
    hospitalDistance: "2.0 km (Columbia Asia)",
    investmentScore: 97,
    rentalYieldPercent: 5.4,
    futureGrowthText: "Unbeatable proximity to Whitefield IT cluster delivers top-tier capital appreciation and maximum rental yield.",
    safeToBuy: true,
    aiVerdict: "TOP TIER BUY. Flagship township by Prestige with prime Whitefield transit location.",
    cribrScore: 96,
    cribrScoreBreakdown: {
      builderReliability: 97,
      constructionProgress: 15,
      locationTransit: 98,
      appreciationYield: 98,
      reraSafety: 97,
      densityLivability: 91
    },
    winnerBadges: {
      isBestLuxury: true,
      isBestInvestment: true
    },
    images: [
      "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"
    ],
    aiInsights: [
      { type: "positive", title: "Whitefield Metro & ITPL", description: "Direct 1.71 km proximity to major IT campuses." }
    ],
    mapCoords: { x: 75, y: 25 },
    timeline: [
      { phase: "Excavation & Foundations", status: "in_progress", date: "Jan 2026", description: "8% construction completed" },
      { phase: "Handover", status: "upcoming", date: "Jun 2030", description: "Target completion" }
    ],
    documents: [
      { title: "RERA Certificate PRM/KA/RERA/1251/446/PR/010126/008374", type: "RERA Certificate", verified: true, fileSize: "3.1 MB" }
    ],
    reviews: []
  },
  {
    id: "proj-poetry-of-earth",
    rank: 16,
    name: "Poetry Of Earth",
    builder: "Urban Excellence LLP",
    developer: "Urban Excellence LLP",
    category: "Ready to Move",
    description: "48% completed residential project in Varthur Village with possession in Dec 2028.",
    price: "₹1.41 Cr - ₹4.22 Cr",
    aiScore: 84,
    configurations: "2 BHK, 3 BHK, Penthouse",
    image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800",
    builderId: "builder-urban-excellence-llp",
    location: "Varthur Village, Varthur Hobli, Bangalore",
    localityName: "Varthur Village, Varthur Hobli",
    city: "Bangalore",
    reraNumber: "PRM/KA/RERA/1251/446/PR/281024/007183",
    priceRange: "₹1.41 Cr - ₹4.22 Cr",
    minPriceLakhs: 141,
    maxPriceLakhs: 422,
    pricePerSqft: "₹10,600/sqft",
    densityValue: 136,
    densityText: "136 units/acre",
    commuteScore: 9.2,
    commuteText: "3.79 km to ITPL / Whitefield",
    builderGrade: "B",
    reliabilityScore: 82,
    constructionProgress: 48,
    possessionDate: "Dec 2028",
    googleRating: 4.2,
    reviewsCount: 65,
    complaintsCount: "0",
    activeComplaintsNum: 0,
    totalUnits: "312 Units",
    totalAcres: 2.3,
    status: "safe",
    statusText: "48% Progress - ₹10,600/sqft Attractive Rate",
    delayMonths: 0,
    pros: ["48% construction completed", "Value rate of ₹10,600/sqft near Whitefield", "Exclusive penthouse floor plans"],
    cons: ["High unit density (136 units/acre)", "Compact 2.3 acre plot"],
    amenities: ["Rooftop Garden", "Clubhouse", "Gymnasium", "Children Play Zone"],
    schools: [{ name: "Varthur High School", distance: "1.2 km" }],
    metroDistance: "4.0 km",
    hospitalDistance: "2.8 km",
    investmentScore: 84,
    rentalYieldPercent: 4.8,
    futureGrowthText: "Close proximity to Whitefield IT hub ensures strong tenant absorption.",
    safeToBuy: true,
    aiVerdict: "BUY. Strong pricing and 48% progress for homebuyers targeting Whitefield connectivity.",
    cribrScore: 84,
    cribrScoreBreakdown: {
      builderReliability: 80,
      constructionProgress: 48,
      locationTransit: 92,
      appreciationYield: 86,
      reraSafety: 93,
      densityLivability: 79
    },
    winnerBadges: {},
    images: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800"
    ],
    aiInsights: [],
    mapCoords: { x: 72, y: 30 },
    timeline: [],
    documents: [],
    reviews: []
  }
];

export function getFeaturedProperties(): FullProject[] {
  return MASTER_PROJECTS;
}

export const FEATURED_PROPERTIES = MASTER_PROJECTS;
export const INTELLIGENCE_REPORTS: any[] = [];
export const PREMIUM_PROPERTIES: any[] = MASTER_PROJECTS;
export const INTELLIGENCE_MODULES = PREMIUM_PROPERTIES;

