// Vercel Serverless Function Entrypoint
// We bypass Vercel's TypeScript compilation by using a plain JavaScript file
// and requiring the bundled server output generated by esbuild during the build step.
const appModule = require("../dist/server.cjs");
const app = appModule.default || appModule;

module.exports = app;
